### ISSUE TITLE
Support for Storybook 6's "Controls"

### ISSUE THREAD

**Issue by metasean** [naver/storybook-addon-preview#12]
We're starting a new project, and Storybook-Addon-Preview appears to provide one of the primary functionalities that we're looking to include in our Storybook.  

Unfortunately, the latest Storybook version —6— replaces the old "Knobs" plug-in with a new "Controls" plug-in [1], which is included by default, and more importantly, it appears to replace the "Knobs" plug-in completely.

Do y'all have a timeline for when Storybook-Addon-Preview will be able to use "Controls" instead of "Knobs"?

[1]: https://medium.com/storybookjs/storybook-controls-ce82af93e430
[2]: https://storybook.js.org/addons

**Comment by daybrush** [comment]
@metasean 

Check PR reviews. Thank you :)

**Comment by qpitlove** [comment]
When do you publish this?
@daybrush

**Comment by daybrush** [comment]
@qpitlove 

Not yet. We did the merge, but there are a lot of bugs, so we will fix several problems. Dark mode will also be added.

**Comment by daybrush** [comment]
@qpitlove @metasean 

storybook-addon-preview 2.0.1 is released. Thank you :)
