### ISSUE TITLE
Add `create-react-app` CSB preset for React

### ISSUE THREAD

**Issue by navin-moorthy** [naver/storybook-addon-preview#18]
## Possible implementation

New Presets
- `ReactJS` - `create-react-app`
- `ReactTS` - `create-react-app-typescript`

**Note**
I can raise a PR for this feature, if agreed

**Comment by daybrush** [comment]
@navin-moorthy 

That's a good idea.

However, by default, the "React" tab is a typescript.

If you want, you can add it to the "ReactJS" tab.

**Comment by navin-moorthy** [comment]
Oh, thats fast. Agreed. React can be default to typescript.

Sure, I will raise a PR adding a new tab `ReactJS`

**Comment by daybrush** [comment]
@navin-moorthy 
storybook-addon-preview 2.1.0 is released. Thank you :)

**Comment by navin-moorthy** [comment]
Worked charm. You can close this issue 🎉 .
Thanks again 🚀
