### ISSUE TITLE
`knobs` is always an empy object

### ISSUE THREAD

**Issue by ryuran** [naver/storybook-addon-preview#26]
Hello

I use this plugin to display code sample relatives to selected knobs.
But when I tried to update Storybook to v6 and storybook-addon-preview to v2, all my knobs was `undefined`.

After investigation the object passed through the `template` function is always empty

An extract from the story config where the `console.log(knobs)` print always an empty object.
```javascript
    preview: [
      {
        tab: 'Javascript',
        template: knobs => {
          console.log(knobs) // empty object
          return `<ui-avatar size="${knobs['Size']}"></ui-avatar>`;
        },
        language: 'html',
        copy: false,
      }
    ]
```

An extract from my package.json
```
"@storybook/addon-a11y": "6.1.21",
"@storybook/addon-knobs": "6.1.21",
"@storybook/addon-viewport": "6.1.21",
"@storybook/html": "6.1.21",
"@storybook/theming": "6.1.21",
"storybook-addon-preview": "2.1.0",
```

**Comment by daybrush** [comment]
@ryuran 

storybook-addon-preview 2.1.1 is released. Check it again. Thank you :)

**Comment by ryuran** [comment]
Thank you very much !
It's working like a charm.
