### ISSUE TITLE
Support globals

### ISSUE THREAD

**Issue by ryuran** [naver/storybook-addon-preview#44]
Storybook provide args and globals but `storybook-addon-preview `seems support only args.
Can we add globals support ?

**Comment by daybrush** [comment]
@ryuran 

We will support globals.

It takes a little time.

**Comment by ryuran** [comment]
suggestion:
> add a second parameter `globals` in the `template` function.

use case:
> a global for i18n/l10n (`en-US`, `zh-CN`, etc.) used for a language switch in the storybook toolbar.

**Comment by daybrush** [comment]
@ryuran 

Published storybook-addon-preview@2.3.0-beta.0

Test this version.

A globals object is added to the second parameter.
```js
template: (props, globals) => `code`,
```

#43 

I tried SyntaxHighlighter.
The formatter is also supported, but only "html" is supported.



So in the case of direct typescript, javascript, vue, svelte, you have to set it yourself.
see the guide

https://github.com/daybrush/storybook-addon-preview/tree/global%2344#formatting

**Comment by daybrush** [comment]
@ryuran 

`storybook-addon-preview` 2.3.0 is released.  Thank you :)
